//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_menschmodell : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean openmainmenu
        {
            get
            {
                return SteamVR_Actions.menschmodell_openmainmenu;
            }
        }
        
        public virtual SteamVR_Action_Boolean closeobjectmenus
        {
            get
            {
                return SteamVR_Actions.menschmodell_closeobjectmenus;
            }
        }
        
        public virtual SteamVR_Action_Boolean click
        {
            get
            {
                return SteamVR_Actions.menschmodell_click;
            }
        }
        
        public virtual SteamVR_Action_Boolean calibrate
        {
            get
            {
                return SteamVR_Actions.menschmodell_calibrate;
            }
        }
    }
}
